import { Award, BookOpen, BrainCircuit, GraduationCap, Mail, MapPin, Microscope, Sparkles } from 'lucide-react'
import SocialLinks from '../components/SocialLinks'
import SEO from '../components/SEO'
import { useApp } from '../context/AppContext'
import { SITE } from '../data/site'
import { TEACHING_START_YEAR, yearsSince } from '../utils/dates'

export default function About() {
  const { lang } = useApp()
  const fa = lang === 'fa'
  const teachingYears = yearsSince(TEACHING_START_YEAR)
  const research = fa
    ? ['بینایی ماشین و تشخیص شیء با خانواده‌های YOLO و R-CNN','یادگیری تقویتی و کنترل ترافیک هوشمند','هوش مصنوعی پزشکی و تحلیل تصویر','کنترل غیرخطی، فازی و مدیریت انرژی','سیستم‌های نهفته، IoT و رایانش لبه']
    : ['Computer vision & object detection with YOLO and R-CNN families','Reinforcement learning and intelligent traffic control','Medical AI and image analysis','Nonlinear/fuzzy control and energy management','Embedded systems, IoT and edge computing']
  const credentials = fa ? [
    ['کارشناسی ارشد مهندسی برق – کنترل','دانشگاه بوعلی سینا · ۲۰۱۸–۲۰۲۱','معدل ۳٫۹۱/۴ · رتبه اول ورودی'],
    ['کارشناسی مهندسی برق – کنترل','دانشگاه صنعتی همدان · ۲۰۱۲–۲۰۱۷','پروژه در کنترل کم‌مصرف تهویه و انرژی باد'],
    ['مدرس الکترونیک','وزارت آموزش و پرورش · از ۲۰۱۸',`${teachingYears}+ سال تدریس مدار، PCB، میکروکنترلر و اتوماسیون`]
  ] : [
    ['M.S. Electrical Engineering · Control Systems','Bu-Ali Sina University · 2018–2021','3.91/4 GPA · ranked first in cohort'],
    ['B.S. Electrical Engineering · Control Systems','Hamedan University of Technology · 2012–2017','Thesis on energy-efficient HVAC control and wind power'],
    ['Electronics Teacher','Ministry of Education · since 2018',`${teachingYears}+ years teaching circuits, PCB, microcontrollers and automation`]
  ]
  const certs = fa ? ['دوره ۷۰۰ ساعته مهارت‌های حرفه‌ای تدریس','ابزار دقیق در صنعت','فناوری خودروهای برقی و هیبریدی','مبدل‌های الکترونیک قدرت','HSE','Siemens S7-300/400','کسب‌وکار نوآوری‌محور'] : ['700-hour Professional Teaching Skills program','Instrumentation in Industry','Electric & Hybrid Vehicle Technologies','Power Electronic Converters','HSE','Siemens S7-300/400','Innovation-Based Business']

  return <>
    <SEO pageType="about" path="/about" image="/images/profile.webp" title={fa ? 'درباره پوریا ملکی | بیوگرافی پژوهشی و رزومه علمی' : 'About Pouria Maleki | AI Researcher & Control Systems Engineer'} description={fa ? 'بیوگرافی و پروفایل علمی پوریا ملکی، پژوهشگر هوش مصنوعی و مهندس سیستم‌های کنترل؛ شامل تحصیلات، سابقه تدریس، حوزه‌های پژوهشی، افتخارات و لینک‌های علمی.' : 'Research biography and academic profile of Pouria Maleki: education, teaching experience, AI and control-systems research, awards, scholarly profiles and professional links.'} />
    <main>
      <section className="relative overflow-hidden border-b border-slate-200 py-20 dark:border-slate-800 md:py-28"><div className="hero-grid absolute inset-0"/><div className="container-shell relative grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div className="mx-auto max-w-sm"><img src="/images/profile.webp" width="1200" height="1195" alt={fa ? 'پرتره پوریا ملکی' : 'Portrait of Pouria Maleki'} className="aspect-[4/5] w-full rounded-[2rem] border border-slate-200 object-cover shadow-2xl dark:border-slate-800"/></div><div><div className="eyebrow"><Sparkles size={15}/>{fa ? 'پروفایل رسمی' : 'Official profile'}</div><h1 className="mt-5 text-4xl font-black tracking-[-.04em] sm:text-5xl lg:text-6xl">{fa ? 'پوریا ملکی' : 'Pouria Maleki'}</h1><p className="mt-5 text-xl font-semibold leading-9 text-slate-700 dark:text-slate-300">{fa ? 'پژوهشگر هوش مصنوعی، مهندس برق و متخصص سیستم‌های کنترل' : 'AI Researcher, Electrical Engineer & Control Systems Specialist'}</p><p className="mt-5 max-w-3xl text-lg leading-9 text-slate-600 dark:text-slate-400">{fa ? 'تمرکز من روی تبدیل مدل‌های هوشمند به سیستم‌های مهندسی قابل استفاده است؛ از تشخیص خودرو و کنترل ترافیک تا هوش مصنوعی پزشکی، مدیریت انرژی و سیستم‌های نهفته.' : 'My work focuses on turning intelligent models into usable engineering systems—from vehicle perception and traffic control to medical AI, energy management and embedded/edge systems.'}</p><div className="mt-6 flex items-center gap-2 text-sm font-bold text-slate-500"><MapPin size={16}/>{SITE.location[lang]}</div><SocialLinks className="mt-7"/></div></div></section>

      <section className="section-pad"><div className="container-shell grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><div className="eyebrow"><BrainCircuit size={15}/>{fa ? 'چشم‌انداز پژوهشی' : 'Research direction'}</div><h2 className="section-title mt-4">{fa ? 'مهندسی هوشمند، با تمرکز بر اثر واقعی' : 'Intelligent engineering with real-world impact'}</h2></div><div className="space-y-5 text-lg leading-9 text-slate-600 dark:text-slate-300"><p>{fa ? 'پیشینه من در کنترل، الکترونیک و هوش مصنوعی باعث شده مسئله‌ها را فقط از زاویه مدل یادگیری ماشین نبینم. برای من سنسور، داده، مدل، تصمیم‌گیری و سخت‌افزار همگی بخشی از یک سیستم هستند.' : 'My background in control, electronics and AI means I rarely see a problem as “just a machine-learning model.” Sensors, data, modeling, decision-making and hardware are all parts of the same system.'}</p><p>{fa ? 'در پژوهش‌های منتشرشده روی دیتاست‌های تشخیص خودرو، خودروهای امدادی، پیش‌بینی ریسک سیلاب و مدیریت انرژی کار کرده‌ام و در پایان‌نامه کارشناسی ارشد، یادگیری تقویتی و بینایی ماشین را برای کنترل چراغ راهنمایی ترکیب کردم.' : 'My published work includes vehicle-detection datasets, emergency-vehicle perception, flood-risk prediction and sustainable energy management. My M.S. thesis combined reinforcement learning and computer vision for adaptive traffic-signal control.'}</p></div></div></section>

      <section className="section-pad bg-slate-50 dark:bg-slate-900/40"><div className="container-shell"><div className="eyebrow"><Microscope size={15}/>{fa ? 'حوزه‌های اصلی' : 'Core research areas'}</div><div className="mt-8 grid gap-4 md:grid-cols-2">{research.map((item,i)=><div key={item} className="card flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-blue-500/10 text-sm font-black text-blue-600">0{i+1}</span><span className="pt-2 font-bold">{item}</span></div>)}</div></div></section>

      <section className="section-pad"><div className="container-shell"><div className="eyebrow"><GraduationCap size={15}/>{fa ? 'تحصیلات و آموزش' : 'Education & teaching'}</div><h2 className="section-title mt-4">{fa ? 'پایه دانشگاهی و سابقه تدریس' : 'Academic foundation & teaching experience'}</h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{credentials.map(([title,place,note])=><article key={title} className="card"><h3 className="text-xl font-black">{title}</h3><p className="mt-3 font-bold text-blue-600 dark:text-blue-400">{place}</p><p className="mt-4 leading-7 text-slate-500">{note}</p></article>)}</div></div></section>

      <section className="section-pad bg-slate-950 text-white"><div className="container-shell grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><div className="eyebrow border-white/15 bg-white/5 text-cyan-200"><Award size={15}/>{fa ? 'افتخارات و آموزش‌های تکمیلی' : 'Recognition & continued learning'}</div><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">{fa ? 'یادگیری مستمر در کنار پژوهش و اجرا' : 'Continuous learning alongside research and implementation'}</h2><p className="mt-5 leading-8 text-slate-300">{fa ? 'دو سال پیاپی به‌عنوان فناور برتر استان همدان انتخاب شده‌ام و در کنار پروژه‌های پژوهشی، دوره‌های تخصصی در آموزش، ابزار دقیق، PLC، خودروهای برقی، HSE و الکترونیک قدرت گذرانده‌ام.' : 'I have been recognized as a Top Technologist in Hamedan Province for two consecutive years and continued specialized training across teaching, instrumentation, PLCs, electric vehicles, HSE and power electronics.'}</p></div><div className="flex flex-wrap content-start gap-3">{certs.map(c=><span key={c} className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-bold text-slate-200">{c}</span>)}</div></div></section>

      <section className="section-pad"><div className="container-shell"><div className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm dark:border-slate-800 dark:bg-slate-900 md:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="eyebrow"><BookOpen size={15}/>{fa ? 'هویت علمی آنلاین' : 'Scholarly identity'}</div><h2 className="mt-4 text-3xl font-black">{fa ? 'مقالات، کد و پروفایل‌های علمی در یک نقطه' : 'Papers, code and scholarly profiles in one place'}</h2><p className="mt-4 max-w-3xl leading-8 text-slate-500">{fa ? 'برای بررسی آثار منتشرشده، استنادها، دیتاست‌ها و کدها می‌توانی از Google Scholar، ResearchGate و GitHub استفاده کنی.' : 'Use Google Scholar, ResearchGate and GitHub to verify publications, citations, datasets and code.'}</p></div><a href={`mailto:${SITE.email}`} className="btn-primary"><Mail size={17}/>{fa ? 'تماس مستقیم' : 'Contact directly'}</a></div><SocialLinks className="mt-7"/></div></div></section>
    </main>
  </>
}
