import { ArrowLeft, ExternalLink, Link as LinkIcon, Linkedin, Send } from 'lucide-react'
import { Link, Navigate, useParams } from 'react-router-dom'
import MarkdownContent from '../components/MarkdownContent'
import SEO from '../components/SEO'
import { useApp } from '../context/AppContext'
import { getArticle } from '../data/articles'
import { SITE } from '../data/site'

export default function BlogPost() {
  const { slug } = useParams(); const { lang, t } = useApp(); const article = getArticle(slug)
  if (!article) return <Navigate to={`/404?lang=${lang}`} replace />
  const title = article.title[lang], excerpt = article.excerpt[lang]
  const pageUrl = `${SITE.url}/blog/${article.slug}?lang=${lang}`
  const enc = encodeURIComponent
  return <><SEO path={`/blog/${article.slug}`} title={`${title} | Pouria Maleki`} description={excerpt} image={article.image} type="article" article={article}/><main className="pb-20"><div className="container-shell pt-8"><Link to={`/blog?lang=${lang}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-blue-600"><ArrowLeft size={16}/>{t.blog.back}</Link></div><article className="container-shell mt-8"><header className="mx-auto max-w-4xl"><div className="mb-5 flex flex-wrap gap-2 text-sm font-bold"><span className="rounded-full bg-blue-50 px-3 py-1 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">{article.category[lang]}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-slate-600 dark:bg-slate-800 dark:text-slate-300">{article.date}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-slate-600 dark:bg-slate-800 dark:text-slate-300">{article.readTime} {t.blog.min}</span></div><h1 className="text-4xl font-black leading-tight tracking-[-.035em] sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-6 text-xl leading-9 text-slate-600 dark:text-slate-300">{excerpt}</p></header><div className="mx-auto mt-10 max-w-5xl overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-100 dark:border-slate-800 dark:bg-slate-900"><img src={article.image} alt={title} className="aspect-[16/7] w-full object-cover"/></div><div className="mx-auto mt-10 grid max-w-5xl gap-10 lg:grid-cols-[1fr_210px]"><div className={`prose prose-slate max-w-none dark:prose-invert prose-headings:scroll-mt-24 prose-headings:font-black prose-a:text-blue-600 prose-img:rounded-2xl ${lang === 'fa' ? 'prose-p:leading-9' : 'prose-p:leading-8'}`}><MarkdownContent content={article.content[lang]}/>{article.sourceUrl && <p className="not-prose mt-10"><a href={article.sourceUrl} target="_blank" rel="noreferrer" className="btn-secondary">{t.blog.source}<ExternalLink size={17}/></a></p>}</div><aside className="lg:sticky lg:top-24 lg:self-start"><div className="rounded-2xl border border-slate-200 p-4 dark:border-slate-800"><div className="mb-3 text-sm font-bold">{t.blog.share}</div><div className="flex gap-2 lg:grid"><a className="share-btn" target="_blank" rel="noreferrer" href={`https://www.linkedin.com/sharing/share-offsite/?url=${enc(pageUrl)}`}><Linkedin size={17}/>LinkedIn</a><a className="share-btn" target="_blank" rel="noreferrer" href={`https://t.me/share/url?url=${enc(pageUrl)}&text=${enc(title)}`}><Send size={17}/>Telegram</a><button className="share-btn" onClick={() => navigator.clipboard.writeText(pageUrl)}><LinkIcon size={17}/>{t.blog.copy}</button></div></div></aside></div></article></main></>
}
